// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1KhNvjcNEvAD2EcyS19Ex9QAfbVwHw54',
    appId: '1:300016005231:web:64148be3d29db5a5c11d9a',
    messagingSenderId: '300016005231',
    projectId: 'hairfall-quiz',
    authDomain: 'hairfall-quiz.firebaseapp.com',
    storageBucket: 'hairfall-quiz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBjUJ00NSk8vixLHcqO4rNJtwKy5KH9iI',
    appId: '1:300016005231:android:ea07b4d94af5bf20c11d9a',
    messagingSenderId: '300016005231',
    projectId: 'hairfall-quiz',
    storageBucket: 'hairfall-quiz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaIGb_9aCUe2njgzUymcsnnrVBm1cEdbM',
    appId: '1:300016005231:ios:cbf9b8243be0aa0ac11d9a',
    messagingSenderId: '300016005231',
    projectId: 'hairfall-quiz',
    storageBucket: 'hairfall-quiz.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1KhNvjcNEvAD2EcyS19Ex9QAfbVwHw54',
    appId: '1:300016005231:web:86be8fb6178bc410c11d9a',
    messagingSenderId: '300016005231',
    projectId: 'hairfall-quiz',
    authDomain: 'hairfall-quiz.firebaseapp.com',
    storageBucket: 'hairfall-quiz.firebasestorage.app',
  );
}
